/**
 * 全プロジェクトデータ
 * Gemini AI推薦機能のコンテキストとしても使用
 */

const CATEGORIES = {
  youtube: { label: "YouTube自動化", icon: "🎬", color: "#ff0000" },
  ec: { label: "EC・物販", icon: "🛒", color: "#f59e0b" },
  sns: { label: "SNS・メッセージ", icon: "📱", color: "#8b5cf6" },
  shift: { label: "勤怠・シフト管理", icon: "📅", color: "#10b981" },
  document: { label: "帳票・書類", icon: "📄", color: "#3b82f6" },
  accounting: { label: "経理・給与", icon: "💰", color: "#ef4444" },
  education: { label: "教育・学校", icon: "🎓", color: "#06b6d4" },
  realestate: { label: "不動産", icon: "🏠", color: "#84cc16" },
  email: { label: "メール自動化", icon: "✉️", color: "#ec4899" },
  data: { label: "データ分析", icon: "📊", color: "#6366f1" },
  other: { label: "その他", icon: "⚙️", color: "#64748b" },
};

const PROJECTS = [
  // ============================================================
  // YouTube自動化（Python）
  // ============================================================
  {
    id: "2ch-video",
    title: "2chまとめ動画 全自動生成システム",
    category: "youtube",
    tags: ["Python", "GPT-4", "DALL-E 3", "OpenAI TTS", "MoviePy", "YouTube API"],
    summary: "テーマを入力するだけで、2ch風ネットスラング台本→AI画像→音声→動画を全自動生成しYouTubeに投稿",
    detail: "テーマを1つ入力するだけで、GPT-4が2ch/5ch風のネットスラング台本を自動生成。DALL-E 3やKIE AIで各シーンの画像を生成し、OpenAI TTSで音声合成。MoviePyで動画に組み上げ、YouTube Data APIで自動アップロードまで完結する完全自動パイプラインです。",
    estimatedPrice: "¥150,000〜",
    priceNote: "類似のYouTube自動化システム開発目安",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "kanji-quiz",
    title: "漢字クイズ動画Bot",
    category: "youtube",
    tags: ["Python", "Gemini API", "VOICEVOX", "MoviePy", "YouTube API", "Google Sheets", "Discord"],
    summary: "漢字クイズ動画の生成→投稿→パフォーマンス分析→改善まで全自動。Windowsタスクスケジューラで毎日運用",
    detail: "Gemini APIで漢字クイズの台本を自動生成し、VOICEVOXで日本語音声を合成、MoviePyで動画をレンダリング。YouTube Data API v3で自動投稿し、Analytics APIでパフォーマンスを分析。結果をGoogle Sheetsに記録し、Discord通知で運用状況を把握。Windowsタスクスケジューラで完全無人運用しています。",
    estimatedPrice: "¥150,000〜",
    priceNote: "分析機能付き動画自動化システム",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "greatman-words",
    title: "偉人名言 AI動画ジェネレーター",
    category: "youtube",
    tags: ["Python", "Claude 3.5", "GPT-4", "DALL-E 3", "VOICEVOX", "MoviePy", "YouTube API", "Google Drive"],
    summary: "偉人・哲学者の言葉をテーマに15分前後の教養系YouTube動画を全自動生成・投稿",
    detail: "Claude 3.5 SonnetやGPT-4で教養系台本を生成し、DALL-E 3やnanobananaで高品質な画像を生成。VOICEVOXで音声合成後、MoviePyで15分前後の本格動画に仕上げます。YouTube/Drive/Sheets APIと連携し、Discord通知付きで完全自動運用。",
    estimatedPrice: "¥200,000〜",
    priceNote: "長尺動画の全自動生成システム",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "cutout-short",
    title: "YouTube切り抜きショート自動化",
    category: "youtube",
    tags: ["Python", "FastAPI", "faster-whisper", "Gemini API", "ffmpeg", "GitHub Actions", "Cloud Run", "Docker"],
    summary: "横長YouTube動画からAIがハイライトを抽出し、ショート動画に自動変換。複数YouTuber対応で毎日自動投稿",
    detail: "Google Driveに動画を置くだけで、faster-whisperで文字起こし→Gemini APIでハイライト区間を抽出→ffmpegで9:16にリサイズ・レンダリング→YouTube自動アップロード。複数YouTuberのチャンネルに対応し、GitHub Actions（毎日12:00 JST）とCloud Runで完全自動運用。FastAPIのWebUIで管理可能。",
    estimatedPrice: "¥200,000〜",
    priceNote: "マルチチャンネル対応の動画自動化",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "sleep-music",
    title: "睡眠音楽チャンネル自動運用（Cozy Night Room）",
    category: "youtube",
    tags: ["Python", "Suno AI", "ffmpeg", "YouTube API", "GitHub Actions", "Nano Banana"],
    summary: "90分の睡眠・LoFi音楽動画を毎日自動生成してYouTubeに投稿。AI作曲+AI画像の完全自動パイプライン",
    detail: "Suno AI（KIE AI経由）でLoFi/睡眠音楽を自動作曲し、Nano Bananaで猫キャラ「Mochi」付きコージーな夜室画像を生成。ffmpegで90分の動画にレンダリングし、YouTube APIで自動投稿。GitHub Actions（毎日17:00 JST）で完全無人運用中。",
    estimatedPrice: "¥150,000〜",
    priceNote: "AI作曲+動画生成の自動化",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "youtube-data-factory",
    title: "YouTubeデータ収集・解析ツール",
    category: "data",
    tags: ["Python", "YouTube Data API", "Whisper", "Discord"],
    summary: "指定チャンネルの全動画を取得し、再生数上位50%を全文字起こし+軽量解析してデータ出力",
    detail: "YouTube Data APIで指定チャンネルの全動画メタデータを収集。再生数上位50%の動画をWhisperで全文字起こしし、軽量解析を実行。JSONL/CSV/TXTで出力し、Discord通知で完了を通知。競合分析やコンテンツ戦略の立案に活用。",
    estimatedPrice: "¥80,000〜",
    priceNote: "データ収集+文字起こしツール",
    image: null,
    featured: true,
    type: "python",
  },

  // ============================================================
  // EC・物販自動化（Python）
  // ============================================================
  {
    id: "ebay-research",
    title: "eBayリサーチ支援システム",
    category: "ec",
    tags: ["Python", "eBay API", "楽天API", "Amazon PA-API", "Gemini API", "GAS", "Google Sheets", "GitHub Actions"],
    summary: "スプレッドシートにeBay URLを貼るだけで、国内仕入れ先を自動検索し利益計算。GAS+GitHub Actionsで全自動",
    detail: "Google スプレッドシートにeBay商品URLを貼ると、GASがGitHub Actionsをトリガー。eBay Browse APIで商品情報を取得後、Gemini APIで最適な検索クエリを生成し、楽天・Amazon PA-APIで国内仕入れ先を自動検索。手数料・送料を含めた利益計算結果をシートに自動書き戻し。fee_rules.yamlで手数料ルールも柔軟に設定可能。",
    estimatedPrice: "¥150,000〜",
    priceNote: "API連携リサーチシステム",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "suzuri-shop",
    title: "SUZURIステッカー自動出品システム",
    category: "ec",
    tags: ["Python", "Gemini API", "KIE AI", "SUZURI API", "Google Sheets", "Discord", "GitHub Actions"],
    summary: "毎日トレンド分析→ステッカー10件をAI企画→AI画像生成→SUZURIに自動出品。完全無人運用",
    detail: "Gemini APIで市場トレンドデータを分析し、売れ筋ステッカーデザインを10件企画。KIE AI（Nano Banana）で画像を自動生成し、SUZURI APIで商品を自動出品。結果をGoogle Sheetsに記録、Discord通知で報告。GitHub Actionsで毎日自動実行。",
    estimatedPrice: "¥120,000〜",
    priceNote: "AI企画+自動出品システム",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "printify-etsy",
    title: "Printify商品量産バッチツール",
    category: "ec",
    tags: ["Python", "Printify API", "Etsy"],
    summary: "画像URLを入力するとPrintifyに商品を量産作成し、Etsyに一括Publish。CLIで効率的に運用",
    detail: null,
    estimatedPrice: "¥60,000〜",
    priceNote: "API連携の量産ツール",
    image: null,
    featured: false,
    type: "python",
  },

  // ============================================================
  // SNS・メッセージ自動化（Python）
  // ============================================================
  {
    id: "threads-scheduler",
    title: "Threads予約投稿WebApp",
    category: "sns",
    tags: ["Python", "FastAPI", "Supabase", "Threads API", "Gemini API", "Cloud Run", "Docker"],
    summary: "テキストを時間指定で分割投稿。Cloud Schedulerで1時間おきに自動実行するWebアプリ",
    detail: "FastAPI + Supabase(PostgreSQL)で構築したThreads予約投稿管理アプリ。テキストを時間指定で分割し、Meta Threads APIで自動投稿。Cloud Run + Cloud Schedulerで1時間おきにジョブを実行。Gemini APIで投稿内容の最適化も可能。Docker対応。",
    estimatedPrice: "¥100,000〜",
    priceNote: "WebApp + API連携",
    image: null,
    featured: true,
    type: "python",
  },
  {
    id: "line-daily-message",
    title: "LINE毎朝自動メッセージ",
    category: "sns",
    tags: ["Python", "LINE Messaging API", "GitHub Actions"],
    summary: "毎朝7:00 JSTにLINEへ自動メッセージ送信。GitHub Actionsで完全自動運用",
    detail: null,
    estimatedPrice: "¥30,000〜",
    priceNote: "シンプルなAPI連携自動化",
    image: null,
    featured: false,
    type: "python",
  },

  // ============================================================
  // 過去のPythonプロジェクト
  // ============================================================
  {
    id: "auto-blog",
    title: "AIブログ自動投稿システム",
    category: "other",
    tags: ["Python", "Gemini AI", "Vertex AI Imagen", "WordPress XML-RPC", "Google Analytics"],
    summary: "キーワードから競合分析→AI記事生成→AI画像生成→WordPress自動投稿までを全自動化",
    detail: null,
    estimatedPrice: "¥120,000〜",
    priceNote: "ブログ運用自動化",
    image: null,
    featured: false,
    type: "python",
  },
  {
    id: "auto-veo-tube",
    title: "Veo 3 YouTubeショート自動化",
    category: "youtube",
    tags: ["Python", "Google Veo 3", "VOICEVOX", "YouTube API"],
    summary: "Google Veo 3でAI動画を生成し、YouTubeショートとして自動投稿",
    detail: null,
    estimatedPrice: "¥100,000〜",
    priceNote: "AI動画生成+YouTube自動化",
    image: null,
    featured: false,
    type: "python",
  },
  {
    id: "wisdom-shorts",
    title: "心に響く短編動画 自動生成",
    category: "youtube",
    tags: ["Python", "Gemini AI", "YouTube API", "Discord", "GitHub Actions"],
    summary: "心理学的洞察をテーマにしたショート動画を自動生成・投稿",
    detail: null,
    estimatedPrice: "¥100,000〜",
    priceNote: "ショート動画自動化",
    image: null,
    featured: false,
    type: "python",
  },
  {
    id: "comfyui-batch",
    title: "ComfyUIバッチ動画生成ツール",
    category: "other",
    tags: ["Python", "ComfyUI API", "Excel(openpyxl)"],
    summary: "Excelで定義したジョブをComfyUI（Wan2.2）に自動投入し、AI動画を無人で連続生成",
    detail: null,
    estimatedPrice: "¥80,000〜",
    priceNote: "バッチ処理ツール",
    image: null,
    featured: false,
    type: "python",
  },

  // ============================================================
  // Excel VBA 受注案件 — 勤怠・シフト管理
  // ============================================================
  {
    id: "excel-attendance",
    title: "出退勤管理システム",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "従業員の出退勤記録を管理・集計するExcelマクロ。打刻データの自動集計機能付き",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "基本的な勤怠管理",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-clinic-shift",
    title: "クリニック夜間業務シフト表",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "医療施設の夜間業務シフトを自動生成。スタッフ別の業務予定表も出力",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "医療向けシフト管理",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-callcenter-shift",
    title: "コールセンター時間帯別オペレーター管理",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "時間帯別にオペレーターの配置を管理・チェックするシフト管理マクロ",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "コールセンター向け",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-cleaning-shift",
    title: "清掃スタッフ業務予定表",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "清掃スタッフ10名分の業務予定表を自動生成。参加者管理機能付き",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "スタッフ管理",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-shift-fix",
    title: "シフト表マクロ修正・改善",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "既存シフト表マクロのバグ修正・機能改善対応",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "既存マクロの修正",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-overtime",
    title: "超過勤務申請表",
    category: "shift",
    tags: ["Excel VBA"],
    summary: "超過勤務の申請・集計を自動化するExcelシート",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "申請書自動化",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — 帳票・書類自動化
  // ============================================================
  {
    id: "excel-pdf-email",
    title: "PDF化+メール自動送信システム",
    category: "document",
    tags: ["Excel VBA", "Outlook連携"],
    summary: "検収通知書をPDFに変換し、メールで自動送信するVBAマクロ",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "PDF+メール連携",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-version-up",
    title: "部品表 版数管理システム",
    category: "document",
    tags: ["Excel VBA"],
    summary: "設計変更に伴う部品表の版数UPを自動管理。変更通知の取込み機能付き",
    detail: null,
    estimatedPrice: "¥30,000〜",
    priceNote: "製造業向け管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-calendar",
    title: "カレンダー自動出力マクロ",
    category: "document",
    tags: ["Excel VBA", "FILTER関数"],
    summary: "月間カレンダーをVBAで自動生成・出力。FILTER関数版も対応",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "基本的なマクロ開発",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-daily-report",
    title: "日報伝票システム",
    category: "document",
    tags: ["Excel VBA"],
    summary: "日報伝票の入力・管理を自動化。市役所向け修正版含む複数バージョン対応",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "帳票管理システム",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-rice-price",
    title: "米価格改定書類 自動作成",
    category: "document",
    tags: ["Excel VBA"],
    summary: "米の価格改定に伴う書類を自動作成するマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "書類自動作成",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-garbage-format",
    title: "ごみ収集フォーマット自動化",
    category: "document",
    tags: ["Excel VBA"],
    summary: "自治体向けごみ収集スケジュールのフォーマットを自動生成するマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "自治体向けツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-image-insert",
    title: "商品画像一括挿入マクロ",
    category: "document",
    tags: ["Excel VBA"],
    summary: "フォルダ内の商品画像をExcelシートに一括挿入するVBAマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "画像処理マクロ",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-shelf-layout",
    title: "棚割表配信システム",
    category: "document",
    tags: ["Excel VBA"],
    summary: "小売業向けの棚割表を店舗へ配信するシステム。レイアウト登録支援・店格マスタ管理付き",
    detail: null,
    estimatedPrice: "¥50,000〜",
    priceNote: "小売業向け業務システム",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — 経理・給与
  // ============================================================
  {
    id: "excel-business-tax",
    title: "事業所税 計算シート",
    category: "accounting",
    tags: ["Excel VBA"],
    summary: "事業所税の自動計算・申告書類作成を支援するExcelシート",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "税務計算ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-salary-total",
    title: "給与総額 集計シート",
    category: "accounting",
    tags: ["Excel VBA"],
    summary: "従業員の給与データを自動集計するExcelシート",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "給与計算",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-accounts-payable",
    title: "買掛金管理システム",
    category: "accounting",
    tags: ["Excel VBA"],
    summary: "買掛金の管理・集計を行うExcelマクロ。フォルダ構成の整理機能付き",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "経理向け管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-payroll-check",
    title: "支給控除 整合性チェックツール",
    category: "accounting",
    tags: ["Excel VBA"],
    summary: "給与データの支給・控除項目をCSVと照合し、整合性を自動チェックするマクロ",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "データ照合ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-petty-cash",
    title: "小口払い集計表",
    category: "accounting",
    tags: ["Excel VBA"],
    summary: "小口払いの申請・集計を管理するExcelシート",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "経理ツール",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — 教育・学校
  // ============================================================
  {
    id: "excel-grade-report",
    title: "成績表マクロ（最大2000人対応）",
    category: "education",
    tags: ["Excel VBA"],
    summary: "学級(50人)・専科(500人)・学校全体(2000人)の3スケールに対応した成績表自動生成マクロ",
    detail: "小規模から大規模校まで対応する成績表マクロ。学級単位(50人)、専科単位(500人)、学校全体(2000人)の3パターンで成績データを管理・集計。個人票の出力やクラス別の統計も自動生成します。",
    estimatedPrice: "¥40,000〜",
    priceNote: "大規模対応の教育ツール",
    image: null,
    featured: true,
    type: "excel",
  },
  {
    id: "excel-seat-chart",
    title: "座席表ランダム生成",
    category: "education",
    tags: ["Excel VBA"],
    summary: "クラスの座席をランダムに配置する座席表ジェネレーター",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "学校向けツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-timetable",
    title: "時間割・時数管理システム",
    category: "education",
    tags: ["Excel VBA"],
    summary: "学年別（1〜6年生）の時間割作成と授業時数を自動管理するマクロ",
    detail: null,
    estimatedPrice: "¥30,000〜",
    priceNote: "学校向け管理システム",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-individual-report",
    title: "個票作成・印刷マクロ",
    category: "education",
    tags: ["Excel VBA"],
    summary: "児童・生徒の個人票を一括作成し印刷するVBAマクロ。支援リストとの連携機能付き",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "教育支援ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-certificate",
    title: "賞状作成マクロ",
    category: "education",
    tags: ["Excel VBA"],
    summary: "テンプレートに名前やデータを差し込んで賞状を一括作成するマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "テンプレート差し込み",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-race-record",
    title: "徒競走記録管理",
    category: "education",
    tags: ["Excel VBA"],
    summary: "運動会の徒競走記録を入力・集計・順位付けするマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "イベント管理",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — 不動産
  // ============================================================
  {
    id: "excel-realestate-calendar",
    title: "定借実績 管理カレンダーツール",
    category: "realestate",
    tags: ["Excel VBA"],
    summary: "定期借地の実績を年度カレンダー形式で管理するツール。2023〜2024年度対応",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "不動産管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-realestate-dx",
    title: "不動産DX 地主リスト管理システム",
    category: "realestate",
    tags: ["Excel VBA", "Word連携"],
    summary: "地主リストの管理・進捗追跡・指示書出力・初回手紙の自動生成を行う不動産DXシステム",
    detail: "地主リストをExcelで一元管理し、進捗状況をトラッキング。指示書（Word）や初回手紙の自動生成機能付き。不動産営業のDX化を支援する包括的なシステムです。",
    estimatedPrice: "¥50,000〜",
    priceNote: "不動産業務DX",
    image: null,
    featured: true,
    type: "excel",
  },
  {
    id: "excel-realestate-docs",
    title: "不動産物件資料 整理ツール",
    category: "realestate",
    tags: ["Excel VBA"],
    summary: "不動産物件資料のデータを自動整理・集計するExcelシート",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "データ整理ツール",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — メール自動化
  // ============================================================
  {
    id: "excel-gmail-auto",
    title: "Gmail マッチングメール自動作成",
    category: "email",
    tags: ["Excel VBA", "Gmail連携"],
    summary: "マッチング完了メールをExcelデータから自動生成するVBAマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "メール自動化",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-bulk-email",
    title: "400件メール一括送信システム",
    category: "email",
    tags: ["Excel VBA", "Outlook連携"],
    summary: "CSVデータから400件規模のメールを一括自動送信するVBAシステム。重複チェック機能付き",
    detail: "CSVファイルからメールアドレスと本文データを読み込み、Outlook連携で最大400件のメールを自動送信。重複削除機能付きでデータの前処理も自動化。一括メールマーケティングや通知配信に活用。",
    estimatedPrice: "¥30,000〜",
    priceNote: "大量メール送信システム",
    image: null,
    featured: true,
    type: "excel",
  },
  {
    id: "excel-outlook-system",
    title: "Outlook連携メール処理システム",
    category: "email",
    tags: ["Excel VBA", "Outlook連携"],
    summary: "Outlook連携のメール処理を自動化するVBAシステム。6バージョンに渡り改良を重ねた実績あり",
    detail: null,
    estimatedPrice: "¥30,000〜",
    priceNote: "メール業務自動化",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-inquiry-transfer",
    title: "メール内容転記 問い合わせ管理",
    category: "email",
    tags: ["Excel VBA"],
    summary: "メールの問い合わせ内容をExcelに自動転記して一覧管理するシステム",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "問い合わせ管理",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — データ分析
  // ============================================================
  {
    id: "excel-pareto",
    title: "パレート図 自動生成マクロ",
    category: "data",
    tags: ["Excel VBA"],
    summary: "製造業向け。設備チョコ停データからパレート図を自動生成し、改善ポイントを可視化",
    detail: "製造現場の設備停止（チョコ停）データを分析し、パレート図を自動生成するマクロ。昼・夜のシフト別データに対応。停止要因の優先順位を可視化し、改善活動を支援。",
    estimatedPrice: "¥20,000〜",
    priceNote: "製造業向け分析ツール",
    image: null,
    featured: true,
    type: "excel",
  },
  {
    id: "excel-boxplot",
    title: "標準偏差・箱ひげ図 自動生成",
    category: "data",
    tags: ["Excel VBA"],
    summary: "統計データから標準偏差の計算と箱ひげ図を自動生成するマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "統計分析ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-keyword-rank",
    title: "キーワード順位レポート生成",
    category: "data",
    tags: ["Excel VBA"],
    summary: "SEOキーワードの順位データをレポート形式で自動生成するマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "SEO分析ツール",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // Excel VBA 受注案件 — その他
  // ============================================================
  {
    id: "excel-progress",
    title: "審査進捗管理ダッシュボード",
    category: "other",
    tags: ["Excel VBA"],
    summary: "申請書類の一次審査進捗を日別に集計・可視化するダッシュボード。不備修正件数のトラッキング付き",
    detail: null,
    estimatedPrice: "¥25,000〜",
    priceNote: "進捗管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-jr-schedule",
    title: "JR月間・週間工程表",
    category: "other",
    tags: ["Excel VBA"],
    summary: "JR関連業務の月間・週間工程表を管理するマクロ。要注カード検索機能付き",
    detail: null,
    estimatedPrice: "¥20,000〜",
    priceNote: "工程管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-name-sort",
    title: "名簿 並び替え・保存システム",
    category: "other",
    tags: ["Excel VBA", "ODF対応"],
    summary: "名簿データの並び替え・保存方法を整備するマクロ。Excel/ODF両対応",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "データ整理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-labor-roster",
    title: "労働者名簿データ化マクロ",
    category: "other",
    tags: ["Excel VBA"],
    summary: "労働者名簿をデータベース形式に変換するVBAマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "データ変換",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-sales-report",
    title: "営業月報作成マクロ",
    category: "other",
    tags: ["Excel VBA"],
    summary: "営業活動の月次報告書を自動作成するVBAマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "営業向けレポート",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-questionnaire",
    title: "質問事項整理マクロ",
    category: "other",
    tags: ["Excel VBA"],
    summary: "質問事項を分類・整理するVBAマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "データ整理",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-copy-count",
    title: "商品コピー枚数 集計マクロ",
    category: "other",
    tags: ["Excel VBA"],
    summary: "商品のコピー枚数を自動集計するマクロ",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "集計ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-prompt-manager",
    title: "AIプロンプト管理・出力ツール",
    category: "other",
    tags: ["Excel VBA"],
    summary: "AIプロンプトの管理・バージョン管理・出力を行うExcelマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "AI活用支援ツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-inventory",
    title: "バーコードスキャン在庫管理システム",
    category: "ec",
    tags: ["Excel VBA", "JANコード"],
    summary: "JANコード（バーコード）スキャンで入出荷を管理する在庫管理システムの設計・開発",
    detail: null,
    estimatedPrice: "¥40,000〜",
    priceNote: "在庫管理システム",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-inspection",
    title: "楽天/Yahoo商品 検品システム",
    category: "ec",
    tags: ["Excel VBA", "CSV連携"],
    summary: "楽天・Yahoo商品の検品チェックリストを助ネコCSV連携で管理。画像マスタ付き操作マニュアル完備",
    detail: "楽天・Yahooの商品検品を効率化するExcelマクロ。助ネコCSVとの連携で受注データを取り込み、画像マスタで商品を照合。検品チェックリストを自動生成し、操作マニュアル（Word）も付属する実務対応済みシステムです。",
    estimatedPrice: "¥40,000〜",
    priceNote: "EC運営向け検品ツール",
    image: null,
    featured: true,
    type: "excel",
  },
  {
    id: "excel-auto-login",
    title: "Webサービス自動ログイン",
    category: "other",
    tags: ["バッチファイル"],
    summary: "バッチファイルでWebサービスへの自動ログインを実現",
    detail: null,
    estimatedPrice: "¥5,000〜",
    priceNote: "簡易自動化",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-ougl-sales",
    title: "OUGL施設売上表",
    category: "other",
    tags: ["Excel VBA"],
    summary: "施設の売上データを管理・集計するExcel売上表",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "売上管理",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-lesson-macro",
    title: "レッスン教室向けマクロ",
    category: "other",
    tags: ["Excel VBA"],
    summary: "レッスン教室の業務を支援するVBAマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "教室運営支援",
    image: null,
    featured: false,
    type: "excel",
  },

  // ============================================================
  // 自作Excelツール（配布用）
  // ============================================================
  {
    id: "excel-annual-calendar",
    title: "年間カレンダー自動生成",
    category: "document",
    tags: ["Excel VBA"],
    summary: "年間カレンダーをVBAで自動生成。行事・予定の管理に最適",
    detail: null,
    estimatedPrice: "¥10,000〜",
    priceNote: "カレンダーツール",
    image: null,
    featured: false,
    type: "excel",
  },
  {
    id: "excel-instagram-manager",
    title: "Instagram投稿管理マクロ",
    category: "sns",
    tags: ["Excel VBA"],
    summary: "子育て・お金・絵本の3テーマ別にInstagram投稿を管理するExcelマクロ",
    detail: null,
    estimatedPrice: "¥15,000〜",
    priceNote: "SNS管理ツール",
    image: null,
    featured: false,
    type: "excel",
  },
];
